# Copyright (c) Hello Robot, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in the root directory
# of this source tree.

"""Spawn placement for MolmoSpaces and Robocasa (re-export shim).

Implementation lives in ``spawn_geom``, ``spawn_settle``, ``spawn_debug``,
``spawn_molmospaces``, ``spawn_planar``, and ``spawn_robocasa``.
"""

from __future__ import annotations

from emet.simulation.spawn_debug import (
    _spawn_debug_ascii_topdown,
    _spawn_debug_downsample_occ,
    _spawn_debug_emit_topdown,
    _spawn_debug_write_occupancy_png,
    spawn_dbg,
    spawn_debug_enabled,
)
from emet.simulation.spawn_geom import (
    _DEFAULT_MOLMOSPACES_GRID_IN_CLIP_MAX,
    _DEFAULT_MOLMOSPACES_GRID_STEP_M,
    _DEFAULT_MOLMOSPACES_OCC_PRIORITY_MAX,
    _EXTERIOR_GEOM_NAME_SUBSTR,
    _HORIZ_EXTERIOR_MAX_FINITE_M,
    _MIN_UPWARD_CEILING_CLEARANCE_M,
    _bodies_descending_from,
    _clamp_xy_into_rect,
    _coarse_grid_xy_in_clip,
    _erode_xy_rect,
    _geom_body_is_robot,
    _geom_exterior_heuristic,
    _horizontal_cardinal_ray_voids_and_finite,
    _max_xy_distance_to_rect_corners,
    _static_collision_occupancy,
    _xy_rect_area_m2,
    collision_scene_xy_clip_rect,
    compute_spawn_walkable_map_metrics,
    effective_floor_geom_name,
    format_spawn_contact_report,
    format_spawn_floor_alignment_report,
    horizontal_spawn_rejects_exterior_tongue,
    iter_annulus_xy_candidates,
    molmospaces_placed_pose_passes_horizontal_interior_gate,
    resolve_floor_geom_name,
    robocasa_navigable_clearance_field,
    scene_collision_centroid_xy,
    upward_ray_hit_distance,
    walkable_floor_z_at_xy,
    worst_robot_nonfloor_contact_dist,
)
from emet.simulation.spawn_molmospaces import (
    _fallback_spawn_near_clip_center,
    _find_molmospaces_freejoint_xyz_pass,
    _ithor_free_xy_order_by_interior_depth,
    _ithor_occupancy_priority_xy,
    _try_spawn_at_xy_candidates,
    _world_xy_to_occ_cell,
    find_molmospaces_freejoint_xyz,
    want_molmospaces_autoplace,
)
from emet.simulation.spawn_planar import (
    find_planar_base_xyt,
    infer_planar_anchor_body_name,
    planar_spawn_footprint_xy_margin_m,
    try_xlerobot_molmospaces_planar_spawn,
    world_se2_to_planar_qpos,
    write_planar_base_xyt,
)
from emet.simulation.spawn_robocasa import (
    _quat_wxyz_from_planar_yaw,
    _robocasa_autoplace_enabled,
    _robocasa_backward_bias_xy,
    _try_robocasa_freejoint_at_xy_yaw,
    find_robocasa_freejoint_xyz,
    want_robocasa_freejoint_autoplace,
    want_robocasa_planar_autoplace,
)
from emet.simulation.spawn_settle import (
    _first_z_with_nonpenetrating_base,
    _min_robot_collision_geom_bottom_z,
    _min_visual_geom_bottom_z,
    _molmospaces_z_settle_options,
    _post_settle_pose_acceptable,
    _settle_foot_clearance_kw,
    _torso_and_base_body_ids,
    resettle_free_base_z_at_current_xy_preserving_yaw,
    restore_freejoint_base_from_model_qpos0,
    robot_placement_bottom_z,
    settle_free_base_z_to_floor,
    support_collision_body_ids_for_base_z_placement,
    write_freejoint_base_xyzw,
)

__all__ = [
    "_DEFAULT_MOLMOSPACES_GRID_IN_CLIP_MAX",
    "_DEFAULT_MOLMOSPACES_GRID_STEP_M",
    "_DEFAULT_MOLMOSPACES_OCC_PRIORITY_MAX",
    "_EXTERIOR_GEOM_NAME_SUBSTR",
    "_HORIZ_EXTERIOR_MAX_FINITE_M",
    "_MIN_UPWARD_CEILING_CLEARANCE_M",
    "_bodies_descending_from",
    "_clamp_xy_into_rect",
    "_coarse_grid_xy_in_clip",
    "_erode_xy_rect",
    "_fallback_spawn_near_clip_center",
    "_find_molmospaces_freejoint_xyz_pass",
    "_first_z_with_nonpenetrating_base",
    "_geom_body_is_robot",
    "_geom_exterior_heuristic",
    "_horizontal_cardinal_ray_voids_and_finite",
    "_ithor_free_xy_order_by_interior_depth",
    "_ithor_occupancy_priority_xy",
    "_max_xy_distance_to_rect_corners",
    "_min_robot_collision_geom_bottom_z",
    "_min_visual_geom_bottom_z",
    "_molmospaces_z_settle_options",
    "_post_settle_pose_acceptable",
    "_quat_wxyz_from_planar_yaw",
    "_robocasa_autoplace_enabled",
    "_robocasa_backward_bias_xy",
    "_settle_foot_clearance_kw",
    "_spawn_debug_ascii_topdown",
    "_spawn_debug_downsample_occ",
    "_spawn_debug_emit_topdown",
    "_spawn_debug_write_occupancy_png",
    "_static_collision_occupancy",
    "_torso_and_base_body_ids",
    "_try_robocasa_freejoint_at_xy_yaw",
    "_try_spawn_at_xy_candidates",
    "_world_xy_to_occ_cell",
    "_xy_rect_area_m2",
    "collision_scene_xy_clip_rect",
    "compute_spawn_walkable_map_metrics",
    "effective_floor_geom_name",
    "find_molmospaces_freejoint_xyz",
    "find_planar_base_xyt",
    "find_robocasa_freejoint_xyz",
    "format_spawn_contact_report",
    "format_spawn_floor_alignment_report",
    "horizontal_spawn_rejects_exterior_tongue",
    "infer_planar_anchor_body_name",
    "iter_annulus_xy_candidates",
    "molmospaces_placed_pose_passes_horizontal_interior_gate",
    "planar_spawn_footprint_xy_margin_m",
    "resettle_free_base_z_at_current_xy_preserving_yaw",
    "resolve_floor_geom_name",
    "restore_freejoint_base_from_model_qpos0",
    "robocasa_navigable_clearance_field",
    "robot_placement_bottom_z",
    "scene_collision_centroid_xy",
    "settle_free_base_z_to_floor",
    "spawn_dbg",
    "spawn_debug_enabled",
    "support_collision_body_ids_for_base_z_placement",
    "try_xlerobot_molmospaces_planar_spawn",
    "upward_ray_hit_distance",
    "walkable_floor_z_at_xy",
    "want_molmospaces_autoplace",
    "want_robocasa_freejoint_autoplace",
    "want_robocasa_planar_autoplace",
    "world_se2_to_planar_qpos",
    "worst_robot_nonfloor_contact_dist",
    "write_freejoint_base_xyzw",
    "write_planar_base_xyt",
]
