# Copyright (c) Chris Paxton 2026
#
# Licensed under the Apache License, Version 2.0 (see LICENSE in the repository root).

"""Compatibility re-exports for graph-memory types and helpers.

Prefer ``emet.memory.graph_eqa.types``, ``labels``, ``geom``, and ``count_mcq``.
"""
from emet.memory.graph_eqa.count_mcq import (
    _COUNT_LEADING_WORDS,
    _COUNT_PHRASE_ALIASES,
    _COUNT_QUANTITY_WRAPPERS,
    _COUNT_ROOM_PHRASES,
    _COUNT_SCOPE_PREPOSITION_RE,
    _COUNT_TARGET_BOUNDARY_RE,
    _COUNT_WORD_ALIASES,
    CountTarget,
    _collapse_count_nodes_spatially,
    _count_phrase_matches,
    _count_room_scope_tokens,
    _count_target_from_stem,
    _count_tokens,
    _count_word_forms,
    _count_word_matches,
    _strip_count_wrappers,
)
from emet.memory.graph_eqa.eqa.graph_eqa_siglip import SIGLIP_CONFIRM_THRESHOLD, SIGLIP_PRESENT_THRESHOLD
from emet.memory.graph_eqa.geom import (
    _ROOM_WORDS,
    _inside_bounds,
    _near,
    _node_is_room,
    _on,
    _on_floor,
)
from emet.memory.graph_eqa.labels import (
    _ACTION_LOOK_RE,
    _ACTION_READ_RE,
    _GRAPH_CANDIDATE_COUNT_DISCLAIMER,
    _LANDMARK_GENERIC_TOKENS,
    _OBJECT_LABEL_ALIASES,
    _QUESTION_LANDMARK_BOOST,
    _QUESTION_STOPWORDS,
    _QUESTION_VERB_FILLERS,
    _location_mcq_weak_tokens,
    _object_match_tokens,
    consolidate_relevant_keywords,
    countable_primary_label_matches,
    distinctive_choice_tokens,
    finder_label_texts,
    format_graph_node_candidates,
    heuristic_relevant_objects,
    heuristic_relevant_phrases,
    label_matches_relevant_object,
    labels_are_semantic_graph_hypothesis,
    location_mcq_landmark_phrases,
    node_display_name,
    parse_eqa_action,
    question_stem_for_keywords,
)
from emet.memory.graph_eqa.types import (
    _RECALL_SOURCE_TIER,
    _WEAK_SIGLIP_FIND_TOKENS,
    GT_BODY_DESC_PREFIX,
    GraphNavigationSample,
    GraphNode,
    GraphObservation,
    NavHypothesis,
    RelationBelief,
    VerifyResult,
    is_ground_truth_node,
)

__all__ = [
    "CountTarget",
    "GT_BODY_DESC_PREFIX",
    "GraphNavigationSample",
    "GraphNode",
    "GraphObservation",
    "NavHypothesis",
    "RelationBelief",
    "SIGLIP_CONFIRM_THRESHOLD",
    "SIGLIP_PRESENT_THRESHOLD",
    "VerifyResult",
    "_ACTION_LOOK_RE",
    "_ACTION_READ_RE",
    "_COUNT_LEADING_WORDS",
    "_COUNT_PHRASE_ALIASES",
    "_COUNT_QUANTITY_WRAPPERS",
    "_COUNT_ROOM_PHRASES",
    "_COUNT_SCOPE_PREPOSITION_RE",
    "_COUNT_TARGET_BOUNDARY_RE",
    "_COUNT_WORD_ALIASES",
    "_GRAPH_CANDIDATE_COUNT_DISCLAIMER",
    "_LANDMARK_GENERIC_TOKENS",
    "_OBJECT_LABEL_ALIASES",
    "_QUESTION_LANDMARK_BOOST",
    "_QUESTION_STOPWORDS",
    "_QUESTION_VERB_FILLERS",
    "_RECALL_SOURCE_TIER",
    "_ROOM_WORDS",
    "_WEAK_SIGLIP_FIND_TOKENS",
    "_collapse_count_nodes_spatially",
    "_count_phrase_matches",
    "_count_room_scope_tokens",
    "_count_target_from_stem",
    "_count_tokens",
    "_count_word_forms",
    "_count_word_matches",
    "_inside_bounds",
    "_location_mcq_weak_tokens",
    "_near",
    "_node_is_room",
    "_object_match_tokens",
    "_on",
    "_on_floor",
    "_strip_count_wrappers",
    "consolidate_relevant_keywords",
    "countable_primary_label_matches",
    "distinctive_choice_tokens",
    "finder_label_texts",
    "format_graph_node_candidates",
    "heuristic_relevant_objects",
    "heuristic_relevant_phrases",
    "is_ground_truth_node",
    "label_matches_relevant_object",
    "labels_are_semantic_graph_hypothesis",
    "location_mcq_landmark_phrases",
    "node_display_name",
    "parse_eqa_action",
    "question_stem_for_keywords",
]
