#!/usr/bin/env python3
# Copyright (c) Chris Paxton 2026
#
# Licensed under the Apache License, Version 2.0 (see LICENSE in the repository root).

"""Generate the large TAMP clutter episode registry across many MolmoSpaces scenes.

Writes ``configs/ovmm/clutter_episodes_large.yaml`` with **200** deterministic
episode templates (offline — no sim, no scatter, no validity probe):

  * robots: rby1 over iTHOR train indices 0..N-1 (default N=22, latch), plus
    stretch / innate_mars / nori over indices 0..5.
  * cleanup: n_objects in {3, 6} at 0.8 / 1.1 m (open ring).
  * nav_goal: n_objects=8 at 0.5 m with ``tight_ring`` (closed blocking ring),
    landmarks rotated across ``NAV_GOAL_LANDMARKS`` plus one ``auto`` row.
  * manip_mode: rby1 ``latch``; stretch / innate_mars / nori ``sim`` (floor
    objects at z≈0.02 m; Nori IK bottoms out ~0.29 m). Use ``--manip-mode latch``
    at eval time for a latch experiment.

Live scatter + the GT probe run at eval time. Scored nav_goal rows require
``episode_valid`` (probe says blocked). Run::

  uv run python scripts/generate_tamp_clutter_registry.py [--output ...] [--rby1-scenes N]

Then::

  uv run python scripts/eval_tamp_clutter.py --episodes configs/ovmm/clutter_episodes_large.yaml --dry-run
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from emet.eval.tamp_clutter import NAV_GOAL_LANDMARKS

REPO = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO / "configs" / "ovmm" / "clutter_episodes_large.yaml"

# (robot, base sim config, max scene index)
ROBOT_SCENES = {
    "rby1": ("configs/sim/molmospaces_ithor_train_0.yaml", 29),
    "stretch": ("configs/sim/molmospaces_ithor_train_stretch_0.yaml", 5),
    "innate_mars": ("configs/sim/molmospaces_ithor_train_innate_mars_0.yaml", 5),
    "nori": ("configs/sim/molmospaces_ithor_train_nori_0.yaml", 5),
}

# Floor clutter: nori/mars latch cannot reliably reach z≈0.02 m.
ROBOT_MANIP_MODE = {
    "rby1": "latch",
    "stretch": "sim",
    "innate_mars": "sim",
    "nori": "sim",
}

# Per scene: (mode, n_objects, landmark_or_None, scatter_radius_m, tight_ring)
EPISODE_TEMPLATES = (
    ("cleanup", 3, None, 0.8, False),
    ("cleanup", 6, None, 1.1, False),
    ("nav_goal", 8, None, 0.5, True),
    ("nav_goal", 8, None, 0.5, True),
    ("nav_goal", 8, "auto", 0.5, True),
)


def generate(robots: dict[str, tuple[str, int]], templates: tuple[tuple, ...]) -> list[dict]:
    episodes: list[dict] = []
    for robot, (sim, max_index) in robots.items():
        n_scenes = max_index + 1
        manip = ROBOT_MANIP_MODE[robot]
        for scene_index in range(n_scenes):
            for t_i, (mode, n_objects, landmark, radius, tight_ring) in enumerate(templates):
                # Rotate landmarks across the set; deterministic seed per scene/template.
                if mode == "nav_goal" and landmark is None:
                    landmark = NAV_GOAL_LANDMARKS[(scene_index + t_i) % len(NAV_GOAL_LANDMARKS)]
                ep_id = f"ithor_{mode}_{scene_index:02d}_{robot}_n{n_objects}"
                if landmark and landmark != "auto":
                    ep_id += f"_{landmark.lower()}"
                if t_i >= 2:
                    ep_id += f"_{t_i}"
                seed = (scene_index * 97 + t_i * 31) % (2**31)
                ep = {
                    "id": ep_id,
                    "tier": "S2" if scene_index >= 2 else "S1",
                    "sim": sim,
                    "robot": robot,
                    "scene_index": scene_index,
                    "mode": mode,
                    "n_objects": n_objects,
                    "scatter_radius_m": radius,
                    "success_radius_m": 0.6 if mode == "nav_goal" else 0.5,
                    "seed": seed,
                    "tight_ring": bool(tight_ring),
                    "manip_mode": manip,
                }
                if mode == "cleanup":
                    ep["bin_query"] = "GarbageCan"
                else:
                    ep["goal_landmark"] = landmark
                    ep["bin_query"] = "GarbageCan"
                episodes.append(ep)
    return episodes


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", type=str, default=str(DEFAULT_OUTPUT))
    p.add_argument("--rby1-scenes", type=int, default=22, help="iTHOR train indices for rby1 (1..30)")
    args = p.parse_args()

    robots = dict(ROBOT_SCENES)
    base_sim, _ = robots["rby1"]
    robots["rby1"] = (base_sim, int(args.rby1_scenes) - 1)

    episodes = generate(robots, EPISODE_TEMPLATES)
    out = Path(args.output).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Generated by scripts/generate_tamp_clutter_registry.py -- do not hand-edit.\n"
        + yaml.safe_dump({"episodes": episodes}, sort_keys=False),
        encoding="utf-8",
    )
    from emet.eval.tamp_clutter import load_clutter_episodes

    n = len(load_clutter_episodes(out))
    robots_seen = sorted({e["robot"] for e in episodes})
    modes = {e["mode"] for e in episodes}
    print(f"Wrote {n} episodes to {out} (robots={robots_seen}, modes={sorted(modes)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
